/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-13 07:59:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._7;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.*;

public final class guess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      entity.GuessNumber GuessNumber = null;
      synchronized (session) {
        GuessNumber = (entity.GuessNumber) _jspx_page_context.getAttribute("GuessNumber", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (GuessNumber == null){
          GuessNumber = new entity.GuessNumber();
          _jspx_page_context.setAttribute("GuessNumber", GuessNumber, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"  href=\"guess.css\">\r\n");
      out.write("<title>猜数字游戏</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h1>欢迎来到猜数字游戏界面！</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"box\" style=\"border: 2px solid #eeeeee; margin-left: 500px; width: 500px;\">\r\n");
      out.write("\t\t<p>猜一猜!</p>\r\n");
      out.write("\t\t<div class=\"container1\">\r\n");
      out.write("\t\t\t<p id=\"rules\">游戏规则如下：</br>\r\n");
      out.write("\t\t\t游戏会生成一个数字，请你猜一猜这个数字？若数字太大或太小，系统会给出提示，您只有三次机会哦！猜对即获胜。</p>\r\n");
      out.write("\t\t\t<div class=\"text-new\">\r\n");
      out.write("\t\t\t<form action=\"getNumber.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t");
  GuessNumber.setNumber(100);
				    int number = GuessNumber.getNumber();		 
				 
      out.write("\r\n");
      out.write("\t\t\t\t ");
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("GuessNumber"), "number",
number);
      out.write("\r\n");
      out.write("\t\t\t\t请输入数字：\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"num\" id=\"input_num\"></input></br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"guessnumber\" id=\"guessnumber\" style=\"display:none\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${number }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></br>\r\n");
      out.write("\t\t\t    <button  name=\"getnum\" value=\"\" type=\"submit\" onclick=\"sell()\">判断该数字是否正确</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    window.onload = function(){\r\n");
      out.write("    \tvar sell= function(){\r\n");
      out.write("    \t\tvar num = document.getElementById(\"button_num\");\r\n");
      out.write("    \t\tvar input_num = num.value;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
