/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-17 02:52:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.mycontrol;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.educoder.entity.*;

public final class controllist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");

String path = request.getContextPath();
String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
List<Goods> goods_clist = (List<Goods>)request.getAttribute("goods_clist");


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/layer/layer.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/js/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/css/bootstrap.min.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/css/form.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/css/userInfo.css\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\r\n");
      out.write("<!-- 引入facicon.ico网页图标 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("css/newGoods.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery-1.11.3.js\"></script>\r\n");
      out.write("<title>shopsInfo</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main-page\">\r\n");
      out.write("\t\t<div class=\"head-page\">\r\n");
      out.write("\t\t\t<p>欢迎来到商家主界面 !</p>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div class=\"buycars-container\">\r\n");
      out.write("\t\t<div class='w'>\r\n");
      out.write("\t\t\t<div class='all'>\r\n");
      out.write("\t\t\t\t<em>待新提交的商品</em>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"all-thead\">\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-goods\">商品</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-price\">单价</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-num\">数量</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-from\">来源</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-img\">图片(网址)</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-description\">简介</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-classfiy\">类别</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"s-thead\">\r\n");
      out.write("\t\t");

		 if(goods_clist!=null){
		    	for(int i=0;i<goods_clist.size();i++){
		    		Goods goods = goods_clist.get(i);
		    		String str = "<div class='goods-item'><div class='s-id'>"+goods.getGoodsId()+"</div><div class='s-goods'>"+goods.getGoodsName()+"</div> <div class='s-price'>"+goods.getGoodsPrice()+"</div>"
		    				   +" <div class='s-num'>"+goods.getGoodsNum()+"</div> <div class='s-from'>"+goods.getGoodsFrom()+"</div> "
		    				   +"<div class='s-img'>"+goods.getGoodsImg()+"</div> <div class='s-description'>"+goods.getGoodsDescribe()+"</div> <div class='s-classfiy'> "+goods.getGoodsClass()+"</div><button class='ag-goods'>同意</button><button class='de-goods'>拒绝</button> </br></div> ";
			    	out.println(str);
			    }
		    	
		    }  
		 
		
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<form action=\"mycontrol.jsp\" method=\"post\" class=\"goodsform\" onsubmit =\"return newcheck1()\"><button type=\"submit\">确认提交</button> 您拒绝的商品单号如下:</form>\r\n");
      out.write("\t  \t<form action=\"mycontrol.jsp\" method=\"post\" class=\"goods_agree\" onsubmit =\"return newcheck2()\"><button type=\"submit\">确认提交</button> 您同意的商品单号如下:</form>\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("var num1 = 0;\r\n");
      out.write("var  num2 = 0;\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("$(\".de-goods\").click(function(){\r\n");
      out.write("\tnum1++;\r\n");
      out.write(" var res = confirm(\"确定删除该商品请求吗？\")\r\n");
      out.write("if(res){\r\n");
      out.write("\t$(this).parents(\".goods-item\").remove();\r\n");
      out.write("\t$(\".goodsform\").append(\"<input name='de-id\"+num1+\"' value = '\"+$(this).siblings(\".s-id\").html()+\"'>\");\r\n");
      out.write("}\t \r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//同意\r\n");
      out.write("$(\".ag-goods\").click(function(){\r\n");
      out.write("\tnum2++;\r\n");
      out.write(" var res = confirm(\"确定同意该商品请求吗？\")\r\n");
      out.write("if(res){\r\n");
      out.write("\t$(this).parents(\".goods-item\").remove();\r\n");
      out.write("\t$(\".goods_agree\").append(\"<input name='ag-id\"+num2+\"' value = '\"+$(this).siblings(\".s-id\").html()+\"'>\");\r\n");
      out.write("}\t \r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("var f1=0;\r\n");
      out.write("var f2=0;\r\n");
      out.write("function newcheck1(){\r\n");
      out.write("\tif(f1==0){\r\n");
      out.write("\t\t$(\".goodsform\").append(\"    已经拒绝的数量:<input name='de-num' value = '\"+num1+\"'>\");\r\n");
      out.write("\t\tf1=1;\r\n");
      out.write("\t}\t\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function newcheck2(){\r\n");
      out.write("\tif(f2==0){\r\n");
      out.write("\t\t\t$(\".goods_agree\").append(\"    已经同意的数量:<input name='ag-num' value = '\"+num2+\"'>\");\r\n");
      out.write("\t\t\tf2 =1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
