/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-13 13:20:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test01;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _5_002dindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>网上试题自动评判——试题</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href = \"5.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  <form action=\"5.jsp\" method=\"post\">\r\n");
      out.write("      一、  2+3=？<br>\r\n");
      out.write("      <input type=\"radio\" name=\"r1\" value=\"2\" checked=\"checked\">2\r\n");
      out.write("      <input type=\"radio\" name=\"r1\" value=\"3\">3\r\n");
      out.write("      <input type=\"radio\" name=\"r1\" value=\"4\">4\r\n");
      out.write("      <input type=\"radio\" name=\"r1\" value=\"5\">5<br>\r\n");
      out.write("      二、下列哪些是偶数？<br>\r\n");
      out.write("      <input type=\"checkbox\" name=\"c1\" value=\"2\">2\r\n");
      out.write("      <input type=\"checkbox\" name=\"c1\" value=\"3\">3\r\n");
      out.write("      <input type=\"checkbox\" name=\"c1\" value=\"4\">4\r\n");
      out.write("      <input type=\"checkbox\" name=\"c1\" value=\"5\">5<br>\r\n");
      out.write("      三、下列哪些是动态网页？<br>\r\n");
      out.write("      <select  size=\"4\" name=\"list1\" multiple=\"multiple\">\r\n");
      out.write("          <option value=\"asp\">ASP</option>\r\n");
      out.write("          <option value=\"php\">PHP</option>\r\n");
      out.write("          <option value=\"jsp\">JSP</option>\r\n");
      out.write("          <option value=\"html\">HTML</option>\r\n");
      out.write("      </select><br>\r\n");
      out.write("      四、下列组件哪个是服务器端的？<br>\r\n");
      out.write("      <select size=\"1\" name=\"list2\">\r\n");
      out.write("          <option value=\"jsp\">JSP</option>\r\n");
      out.write("          <option value=\"servlet\">SERVLET</option>\r\n");
      out.write("          <option value=\"java\">JAVA</option>\r\n");
      out.write("          <option value=\"jdbc\">JDBC</option>\r\n");
      out.write("      </select><br>\r\n");
      out.write("      五、在服务器端用来接受用户请求的对象是：\r\n");
      out.write("      <input tpye=\"text\" size=\"10\" name=\"text1\"><br>\r\n");
      out.write("      <div align=\"left\" class=\"mybutton\">\r\n");
      out.write("          <blockquote>\r\n");
      out.write("              <input type=\"submit\" value=\"提交\" name=\"button1\">\r\n");
      out.write("              <input type=\"reset\" value=\"重置\" name=\"button2\">\r\n");
      out.write("          </blockquote>\r\n");
      out.write("      </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
