/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-16 01:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.educoder.entity.*;

public final class goodsInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
User user = (User)request.getSession().getAttribute("user");

//System.out.println(user.toString());
//成功获取数据当前用户已登录
//待实现的功能部分，当用户没有登录时，无法进行购物，则需要进行判断

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-1.11.3.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/goodsinfo.css\">\r\n");
      out.write("<title>my goodsInfo</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"uu\"><a href=\"#b_form\">查看添加的信息</a> <a href='#topp'>返回页面顶部</a></div>\r\n");
      out.write("   <div class=\"tabs\" id =\"topp\">\r\n");
      out.write("   <div class=\"tabs_title\">\r\n");
      out.write("   <div class=\"title_item\" id=\"title1\" >综合</div>\r\n");
      out.write("   <div class=\"title_item\" id=\"title2\">商品</div>\r\n");
      out.write("   <div class=\"title_item\" id=\"title3\">价格</div>\r\n");
      out.write("   </div>   \r\n");
      out.write("   </div>\r\n");
      out.write("\t<div class=\"first_tab\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\tgetgoodslist();\r\n");
      out.write("\tu_buy(); //click事件无效问题js加载获取动态元素\r\n");
      out.write("}\r\n");
      out.write("function checkaddress(){\r\n");
      out.write("\r\n");
      out.write("\tvar uaddress = $(\".u_address\").val();\r\n");
      out.write("\t $(\".buy_form\").append(\"<input name='goodnum' value='\"+buyarr.length+\"'>\");\r\n");
      out.write("\tconsole.log(uaddress);\r\n");
      out.write("\t\tif(uaddress==\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\talert(\"请填写您的地址信息！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"成功添加进入购物车！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn  true;\r\n");
      out.write("}\r\n");
      out.write("var buyarr = [];\r\n");
      out.write("function u_buy(){\r\n");
      out.write("\t \r\n");
      out.write("\tvar text =  $(\".u_buy\");\r\n");
      out.write("\t$(\".first_tab\").after(\"<form onsubmit='return checkaddress()' action='goodsinfo.jsp' method='post' class='buy_form' id='b_form'></form>\")\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".u_buy\").click(function(){\r\n");
      out.write("\t\talert(\"成功加入购物车！\"+$(this).parent().parent().attr(\"id\"));\t\t\r\n");
      out.write("\t\tvar goodsid = $(this).parent().parent().attr(\"id\");\r\n");
      out.write("\t\tbuyarr.push(goodsid);\r\n");
      out.write("\t\taddbuy();\r\n");
      out.write("\t\tvar good = findbuy(goodsid);\r\n");
      out.write("\t\t$(\".buy_form\").prepend(\"<input name='goodsid\"+buyarr.length+\"' value='\"+good.goodsid+\"'><input name='goodsname\"+buyarr.length+\"' value='\"+good.goodsname+\"'><input name='goodsprice\"+buyarr.length+\"' value='\"+good.goodsprice+\"'></from>\");\r\n");
      out.write("\t})\t\r\n");
      out.write("\t$(\".buy_form\").append(\"请填入您的个人收货地址：<input name='uaddress' value='' class='u_address'><button type='submit'>提交购物</button>\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function addbuy(){\r\n");
      out.write("\tfor(var i=0;i<buyarr.length;i++){\r\n");
      out.write("\t\tconsole.log(buyarr[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function findbuy(goodsid){\r\n");
      out.write("\t//定义map数组\r\n");
      out.write("\tvar good ={};\r\n");
      out.write("$.each(good_list.message, function(i, n) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.each(n.goodslist, function(j, m) {\t\t\t\r\n");
      out.write("\t\t\tif(m.goods_id==goodsid){\r\n");
      out.write("\t\t\t\tgood.goodsid = m.goods_id ;//随机生成订单号\r\n");
      out.write("\t\t\t\tgood.goodsname = m.goods_name; \r\n");
      out.write("\t\t\t\tgood.goodsprice = m.goods_price;\r\n");
      out.write("\t\t\t\tgood.goodsimg = m.goods_id +\".jpg\";\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\tconsole.log(good);\r\n");
      out.write("\treturn good;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
