/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-08 00:34:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/css/form.css\">\r\n");
      out.write("<title>shops-register</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main-page\">\r\n");
      out.write("\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t<p>欢迎来到商家注册界面</p>\r\n");
      out.write("\t\t\t<div class=\"local-form\">\r\n");
      out.write("\t\t\t\t<form action=\"Register01.jsp\" method=\"post\" id=\"registerForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-u\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"userId\">\r\n");
      out.write("\t\t\t\t\t\t\t\tshopsId:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userId\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"userName\">\r\n");
      out.write("\t\t\t\t\t\t\t\tshopsName:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userName\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nowpwd\">\r\n");
      out.write("\t\t\t\t\t\t\t\tpassword:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"nowpwd\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"newpwd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t请再次输入密码：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"newpwd\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t Address:<input type=\"text\" name=\"address\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"classify\">\r\n");
      out.write("\t\t\t\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"daily-use\" selected>日常用品</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"electrical\">家用电器</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"school-supplies\">学习用品</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"clothes\">服饰</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"createtime\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"date\" name=\"user_date\" /></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"mybutton\" type=\"submit\" name=\"提交\">注册</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"mybutton\" type=\"\" name=\"取消\">取消</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
