/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-12 07:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
Object message = request.getAttribute("message");
System.out.println("Register"+message);

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/css/form.css\">\r\n");
      out.write("<title>注册用户</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main-page\">\r\n");
      out.write("\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t<p>欢迎来到用户注册界面</p>\r\n");
      out.write("\t\t\t<div class=\"local-form\">\r\n");
      out.write("\t\t\t\t<form  onsubmit=\"return RegisterUser();\"action=\"Register.jsp\" method=\"post\" id=\"registerForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-u\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"model\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"modelId\" size=\"1\" class=\"m_id\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"User\">用户模式User</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"shops\">商家选择模式-Shops</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"mycontorl\">控制选择</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"userId\">\r\n");
      out.write("\t\t\t\t\t\t\t\tuserId:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userId\" class=\"u_id\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"userName\">\r\n");
      out.write("\t\t\t\t\t\t\t\tuserName:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"userName\" class=\"u_name\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nowpwd\">\r\n");
      out.write("\t\t\t\t\t\t\t\tpassword:\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"nowpwd\" class=\"u_p1\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"newpwd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t请再次输入密码：\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"newpwd\" class=\"u_p2\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
  if(message!=null){
					if(message=="wrong")
					out.print("<script>alert('您输入的userId已被占用！请重新输入')</script>");
					else if(message =="ok"){
						out.print("<script>alert('注册成功')</script>");
					}
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"mybutton\" type=\"submit\" name=\"提交\">注册用户</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"mybutton\" type=\"\" name=\"取消\">取消</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"js/jquery-1.11.3.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction RegisterUser() {\r\n");
      out.write("\t\tvar userid = $(\".u_id\").val();\r\n");
      out.write("\t\tvar username = $(\".u_name\").val();\r\n");
      out.write("\t\tvar nowpassword = $(\".u_p1\").val();\r\n");
      out.write("\t\tvar newpassword = $(\".u_p2\").val();\r\n");
      out.write("\t\tif (\"\" == username || \"\" == nowpassword || \"\" == newpassword|| userid ==\"\") {\r\n");
      out.write("\t\t\talert(\"请把信息填写完整！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!(nowpassword==newpassword)) {\r\n");
      out.write("\t\t\talert(\"两次填写的密码不一致哦！请重新填写。\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} \r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
