/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-09 06:44:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class userInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>帐号设置</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("res/css/userInfo.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery-1.11.3.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main-1\">\t\t\r\n");
      out.write("\t\t<div class=\"make-change\">\r\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"m-change\">修改我的个人信息</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h1>我的用户信息</h1>\r\n");
      out.write("\t\t<img src=\"\" width=\"200px\" ; height=\"200px\">\r\n");
      out.write("\t\t<h2>username</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"main-2\">\r\n");
      out.write("\t\t<ul class=\"nowul\">\r\n");
      out.write("\t\t\t<li class=\"number\">电话号码：12345656</li>\r\n");
      out.write("\t\t\t<li class=\"adress\">送货地址：XXX 路 XXXX街</li>\r\n");
      out.write("\t\t\t<li class=\"sighname\">个性签名：本人很有个性，并未留下任何签名</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"main-3\">\r\n");
      out.write("\t\t<p>本人什么记录也没有~~</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvar flag=0;\r\n");
      out.write("\t\t\t$(\".m-change\").click(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t  if(flag==0){\r\n");
      out.write("\t\t\t\t\t\t\t\t  $(\".main-2\").removeClass(\".nowul\");\r\n");
      out.write("\t\t\t\t\t\t\t\t//设置form表单完成数据修改的功能\r\n");
      out.write("\t\t\t\t\t\t\t\tvar str = \"<from action ='Register.jsp' method='post' id='userchangeFrom'><div class='from-u'>\"+\"<ul class='newmessage'>用户名：<input type='text' name='username'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"用户密码：<input type='text' name='userpassword'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"电话号码：<input type='text' name='userphonenum'></br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"用户地址：<input type='text' name='useraddress'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"个性签名：<input type='text' name='usersign'>\" + \"<button class='mybutton' type='submit' name ='提交'>修改信息</button></div></form>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".main-2\").prepend(str);\r\n");
      out.write("\t\t\t\t\t\t\t\tflag++;\r\n");
      out.write("\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
