/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-11 05:48:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._6;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
   

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".login-form {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\t\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-form form {\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\twidth: 350px;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tborder: 5px solid black;\r\n");
      out.write("\tmargin-right:50px;\r\n");
      out.write("\tmargin-top:50px;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("}\r\n");
      out.write(".login-form form ul{\r\n");
      out.write("style-list:none;\r\n");
      out.write("}\r\n");
      out.write(".login-form  ul li{\r\n");
      out.write("border-bottom:1px solid black;\r\n");
      out.write("width:200px;\r\n");
      out.write("style-list:none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".login-form  input {\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write(".login-form button{\r\n");
      out.write("background-color:grey;\r\n");
      out.write("width:100px;\r\n");
      out.write("border-radius:15px;\r\n");
      out.write("height:30px;\r\n");
      out.write("margin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"login-form\">\r\n");
      out.write("\t\t<form  onsubmit=\"return loginUser();\" action=\"../login\" method=\"post\" id=\"loginForm\">\r\n");
      out.write("\t\t<div class=\"form-u\">\r\n");
      out.write("\t\t   <p>欢迎您的登录！</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"userId\">\r\n");
      out.write("\t\t\t\t\tuserId:\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"userId\"></input>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"userName\">\r\n");
      out.write("\t\t\t\t\tuserName:\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"userName\"></input>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"passWord\">\r\n");
      out.write("\t\t\t\t\tpassword:\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"passWord\"></input>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"提交\" >登录</button>\r\n");
      out.write("\t\t\t<button name=\"注册\">注册新用户</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction loginUser() {\r\n");
      out.write("\t\tvar userid = document.getElementById(\"userId\").value.trim();\r\n");
      out.write("\t\tvar username = document.getElementById(\"userName\").value.trim();\r\n");
      out.write("\t\tvar userpassword = documnet.getElementById(\"passWord\").value.trim();\r\n");
      out.write("\t\tif(userid=\"\"||username=\"\"||userpassword=\"\"){\r\n");
      out.write("\t\t\talert(\"请把用户信息填写完整！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
