/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-18 01:41:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.shops;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.educoder.entity.*;

public final class newgoods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>我的购物车</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\r\n");
      out.write("<!-- 引入facicon.ico网页图标 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("css/newGoods.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery-1.11.3.js\"></script>\r\n");
      out.write("<title>shopsInfo</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"buycars-container\">\r\n");
      out.write("\t\t<div class='w'>\r\n");
      out.write("\t\t\t<div class='all'>\r\n");
      out.write("\t\t\t\t<em>待新提交的商品</em>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"all-thead\">\r\n");
      out.write("\t\t \t<div id=\"t\"><button class=\"InsertBtn\">添加商品</button></div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-goods\">商品</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-price\">单价</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-num\">数量</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-from\">来源</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-img\">图片(网址)</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-description\">简介</div>\r\n");
      out.write("\t\t\t\t<div id=\"t\" class=\"t-classfiy\">类别</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"s-thead\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<form action=\"goods.jsp\" method=\"post\" class=\"goodsform\" onsubmit =\"return newcheck()\"></form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var flag=0;\r\n");
      out.write("var num = 1;\r\n");
      out.write("\t$(\".InsertBtn\")\r\n");
      out.write("\t\t\t.click(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\tvar str = \"商品单号：<input class='p-id' name='p-id'> \"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"商品名：<input class='p-goods' name='p-goods'> </br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \" 单价：<input class='p-price' name='p-price'> \"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"数量：<input class='p-num' name='p-num'> \"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"来源：<input class='p-from' name='p-from'> </br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"图片：<input class='p-img' name='p-img'> \"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"简介：<input class='p-description' name='p-description'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"类别：<input class='p-classfiy' name='p-classfiy'> <br>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+\"<button type='submit'style='margin-left:50px'>确认申请</button><button type='reset' style='margin-left:50px'>取消</button>\";\r\n");
      out.write("\t\t\t\t\t\tif(flag==0){\r\n");
      out.write("\t\t\t\t\t\t\t$(\".goodsform\").append(str);\r\n");
      out.write("\t\t\t\t\t\t\tflag=1;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("function newcheck(){\r\n");
      out.write("\t\tvar goodsid = $(\".p-id\").val();\r\n");
      out.write("\t\tvar goodsname = $(\".p-goods\").val();\r\n");
      out.write("\t\tvar goodsprice = $(\".p-price\").val();\r\n");
      out.write("\t\tvar goodsnum = $(\".p-num\").val();\r\n");
      out.write("\t\tvar goodsfrom = $(\".p-from\").val();\r\n");
      out.write("\t\tvar goodsimg = $(\".p-img\").val();\r\n");
      out.write("\t\tvar goodsdescription = $(\".p-description\").val();\r\n");
      out.write("\t\tvar goodsclassfiy = $(\".p-classfiy\").val();\r\n");
      out.write("\t\tvar newgood = [];\r\n");
      out.write("\tnewgood.push(goodsid);\r\n");
      out.write("\tnewgood.push(goodsname);\r\n");
      out.write("\tnewgood.push(goodsprice);\r\n");
      out.write("\tnewgood.push(goodsnum);\r\n");
      out.write("\tnewgood.push(goodsfrom);\r\n");
      out.write("\tnewgood.push(goodsimg);\r\n");
      out.write("\tnewgood.push(goodsdescription);\r\n");
      out.write("\tnewgood.push(goodsclassfiy);\r\n");
      out.write("    for(var i=0;i<newgood.length;i++){\r\n");
      out.write("\t\tif(newgood[i]==\"\"){\r\n");
      out.write("\t\t\talert(\"请将您的信息填写完整! \");\r\n");
      out.write("\t\t\treturn false;\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("   /*表单添加成分*/\r\n");
      out.write("   str = \"<div class='s-order' id ='\"+num+\"'>\"+num+\"</div> <div class='s-id'>\"+goodsid+\"</div><div class='s-goods'>\"+goodsname+\"</div> <div class='s-price'>\"+goodsprice+\"</div>\"\r\n");
      out.write("   +\" <div class='s-num'>\"+goodsnum+\"</div> <div class='s-from'>\"+goodsfrom+\"</div> \"\r\n");
      out.write("   +\"<div class='s-img'>\"+goodsimg+\"</div> <div class='s-description'>\"+goodsdescription+\"</div> <div class='s-classfiy'> \"+goodsclassfiy+\"</div>\"\r\n");
      out.write("\t  console.log(newgood);\r\n");
      out.write("   num++;\r\n");
      out.write("   $(\".s-thead\").prepend(str);\r\n");
      out.write("\t  flag = 0;\r\n");
      out.write("\t  return  true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
